name: "AOC"
on:
  push:
      paths:
        - adventofcode/**
jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Run all
        run: |
          cd adventofcode/2021
          python3 -m unittest discover
